[project]
name = "agent-learn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "black>=25.1.0",
    "dotenv>=0.9.9",
    "litellm>=1.61.15",
    "openai>=1.64.0",
    "opensearch-py>=2.8.0",
    "pydantic>=2.10.6",
]
